---
title: News from Nowhere
subtitle: or An Epoch of Rest
author: William Morris
date: september 2025
rights: "Spectral, 2025."
input-files:
- "01-preface.md"
- "02-chapter1.md"
- "03-chapter2.md"
- "04-chapter3.md"
- "05-chapter4.md"
- "06-chapter5.md"
- "07-chapter6.md"
- "08-chapter7.md"
- "09-chapter8.md"
- "10-chapter9.md"
- "11-chapter10.md"
- "12-chapter11.md"
- "13-chapter12.md"
- "14-chapter13.md"
- "15-chapter14.md"
- "16-chapter15.md"
- "17-chapter16.md"
- "18-chapter17.md"
- "19-chapter18.md"
- "20-chapter19.md"
- "21-chapter20.md"
- "22-chapter21.md"
- "23-chapter22.md"
- "24-chapter23.md"
- "25-chapter24.md"
- "26-chapter25.md"
- "27-chapter26.md"
- "28-chapter27.md"
- "29-chapter28.md"
- "30-chapter29.md"
- "31-chapter30.md"
- "32-chapter31.md"
- "33-chapter32.md"
- "34-postface.md"
- "35-bibliography.md"
isbn-print: "978-1-234567-89-7"
critical: "Preface by E.P. Thompson <br>Postface by Manfredo Tafuri"
editions: "First serialized in *Commonweal* (1890); <br>first book edition by Reeves & Turner, London (1891)."
coverCredit: "Frontispiece of *News from Nowhere*: Entrance to Kelmscott Manor, drawn by Charles March Gere, engraved by W. H. Hooper (Kelmscott Press, 1892)."
---
